### ISSUE TITLE
instruction

### ISSUE THREAD

**Issue by Dmitriy51** [IS4Code/Pawn-DeepL#4]
hi, I followed your instructions and I don't understand what the problem is... it doesn't translate anything, can you correct me?

public OnPlayerText(playpublic OnPlayerText(playerid, const text[])
{
if(text[0] == '+')
{
    DeepL_SetAuthKey("cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx");
    DeepL_Translate(text[1], "RO", "DE", #DeepL_OnTranslationDone);
    }
return 0;
}

public bool:DeepL_OnTranslationDone(bool:success, result[], from[], cookie)
{
	if(success == true){
	SendClientMessageToAllf(0x00FF00FF, result);
       }else SendClientMessageToAllf(0x00FF00FF, "the translation does not work");
	return true;
}

**Comment by IS4Code** [comment]
Hello, is `DeepL_OnTranslationDone` called at all? If there is an error, `result` will contain the error message - what is the content?

**Comment by Dmitriy51** [comment]
yes is called DeepL_OnTranslationDone 
bool:success is:  false
result is:   unexpected end of input

**Comment by IS4Code** [comment]
Well, then it might be caused by `DeepL_SetAuthKey("cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx");`. First of all, that should be called in `OnGameModeInit` (or similar), not before each request. Did you obtain your DeepL API key, or do you actually use `cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx`?

**Comment by Dmitriy51** [comment]
I changed, but the same problem without change

**Comment by IS4Code** [comment]
> Did you obtain your DeepL API key, or do you actually use `cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx`?

**Comment by Dmitriy51** [comment]
cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx yes I updated in OnGameModeInit, and same error send me...

**Comment by IS4Code** [comment]
See the readme:

> To use the plugin, you have to provide your [DeepL authentication key](https://www.deepl.com/docs-api/api-access/authentication/).

> `DeepL_SetAuthKey("cbae67e8-63cd-4f7f-a0c9-a2a32905679d:fx"); // example key`

You will need your own API key.
